<?php
/** @var $block \Magento\Msrp\Pricing\Render\PriceBox */

$priceType = $block->getPrice();
$product = $block->getSaleableItem();
$productId = $product->getId();

$amount = $block->getMsrpPriceCalculator()->getMsrpPriceValue($product);
$finalAmount = $block->getPriceType('final_price')->getValue();

if ($finalAmount < $amount):
$msrpPrice = $block->renderAmount(
    $priceType->getCustomAmount($amount),
    [
        'price_id' => $block->getPriceId() ? $block->getPriceId() : 'old-price-' . $productId,
        'include_container' => false,
        'skip_adjustments' => false
    ]
);
?>

<?php if ($amount) : ?>
    <span class="old-price map-old-price"><?= /* @noEscape */ $msrpPrice ?></span>
    <span class="map-fallback-price normal-price"><?= /* @noEscape */ $msrpPrice ?></span>
<?php endif; ?>
<?php endif; ?>
